export const CURSOS_COMUNS: string[] = [
  "Administração",
  "Agronomia",
  "Arquitetura e Urbanismo",
  "Biomedicina",
  "Ciência da Computação",
  "Ciências Contábeis",
  "Ciências Econômicas",
  "Direito",
  "Educação Física",
  "Enfermagem",
  "Engenharia Civil",
  "Engenharia de Computação",
  "Engenharia de Produção",
  "Engenharia Elétrica",
  "Engenharia Mecânica",
  "Engenharia Química",
  "Farmácia",
  "Fisioterapia",
  "Fonoaudiologia",
  "Gestão Comercial",
  "História",
  "Jornalismo",
  "Letras",
  "Marketing",
  "Medicina",
  "Medicina Veterinária",
  "Nutrição",
  "Odontologia",
  "Pedagogia",
  "Psicologia",
  "Publicidade e Propaganda",
  "Química",
  "Radiologia",
  "Sistemas de Informação",
  "Serviço Social",
  "Terapia Ocupacional",
];
