export type Instituicao = {
  sigla: string;
  nome: string;
};

export const INSTITUICOES_BR: Instituicao[] = [
  { sigla: "FIMCA", nome: "Centro Universitário Aparício Carvalho" },
  { sigla: "UniSALESIANO", nome: "Centro Universitário Católico Salesiano Auxilium" },
  { sigla: "CEUB", nome: "Centro Universitário de Brasília" },
  { sigla: "FMU", nome: "Centro Universitário FMU" },
  { sigla: "Newton Paiva", nome: "Centro Universitário Newton Paiva" },
  { sigla: "São Camilo", nome: "Centro Universitário São Camilo" },
  { sigla: "Estácio", nome: "Universidade Estácio de Sá" },
  { sigla: "Anhanguera", nome: "Faculdade Anhanguera" },
  { sigla: "FAAP", nome: "Fundação Armando Alvares Penteado" },
  { sigla: "FACAMP", nome: "Faculdades de Campinas" },
  { sigla: "FGV", nome: "Fundação Getulio Vargas" },
  { sigla: "IBMEC", nome: "Instituto Brasileiro de Mercado de Capitais" },
  { sigla: "Insper", nome: "Insper Instituto de Ensino e Pesquisa" },
  { sigla: "Mackenzie", nome: "Universidade Presbiteriana Mackenzie" },
  { sigla: "PUC-Campinas", nome: "Pontifícia Universidade Católica de Campinas" },
  { sigla: "PUC Minas", nome: "Pontifícia Universidade Católica de Minas Gerais" },
  { sigla: "PUC-Rio", nome: "Pontifícia Universidade Católica do Rio de Janeiro" },
  { sigla: "PUCRS", nome: "Pontifícia Universidade Católica do Rio Grande do Sul" },
  { sigla: "PUC-SP", nome: "Pontifícia Universidade Católica de São Paulo" },
  { sigla: "PUCPR", nome: "Pontifícia Universidade Católica do Paraná" },
  { sigla: "UEL", nome: "Universidade Estadual de Londrina" },
  { sigla: "UEM", nome: "Universidade Estadual de Maringá" },
  { sigla: "UENP", nome: "Universidade Estadual do Norte do Paraná" },
  { sigla: "UERJ", nome: "Universidade do Estado do Rio de Janeiro" },
  { sigla: "UEPG", nome: "Universidade Estadual de Ponta Grossa" },
  { sigla: "UFAL", nome: "Universidade Federal de Alagoas" },
  { sigla: "UFAM", nome: "Universidade Federal do Amazonas" },
  { sigla: "UFBA", nome: "Universidade Federal da Bahia" },
  { sigla: "UFC", nome: "Universidade Federal do Ceará" },
  { sigla: "UFES", nome: "Universidade Federal do Espírito Santo" },
  { sigla: "UFF", nome: "Universidade Federal Fluminense" },
  { sigla: "UFG", nome: "Universidade Federal de Goiás" },
  { sigla: "UFJF", nome: "Universidade Federal de Juiz de Fora" },
  { sigla: "UFMA", nome: "Universidade Federal do Maranhão" },
  { sigla: "UFMG", nome: "Universidade Federal de Minas Gerais" },
  { sigla: "UFMS", nome: "Universidade Federal de Mato Grosso do Sul" },
  { sigla: "UFMT", nome: "Universidade Federal de Mato Grosso" },
  { sigla: "UFPA", nome: "Universidade Federal do Pará" },
  { sigla: "UFPB", nome: "Universidade Federal da Paraíba" },
  { sigla: "UFPE", nome: "Universidade Federal de Pernambuco" },
  { sigla: "UFPI", nome: "Universidade Federal do Piauí" },
  { sigla: "UFPR", nome: "Universidade Federal do Paraná" },
  { sigla: "UFRGS", nome: "Universidade Federal do Rio Grande do Sul" },
  { sigla: "UFRJ", nome: "Universidade Federal do Rio de Janeiro" },
  { sigla: "UFRN", nome: "Universidade Federal do Rio Grande do Norte" },
  { sigla: "UFRO", nome: "Universidade Federal de Rondônia" },
  { sigla: "UFRPE", nome: "Universidade Federal Rural de Pernambuco" },
  { sigla: "UFRRJ", nome: "Universidade Federal Rural do Rio de Janeiro" },
  { sigla: "UFSC", nome: "Universidade Federal de Santa Catarina" },
  { sigla: "UFSCar", nome: "Universidade Federal de São Carlos" },
  { sigla: "UFSM", nome: "Universidade Federal de Santa Maria" },
  { sigla: "UFT", nome: "Universidade Federal do Tocantins" },
  { sigla: "UFU", nome: "Universidade Federal de Uberlândia" },
  { sigla: "UFV", nome: "Universidade Federal de Viçosa" },
  { sigla: "UFABC", nome: "Universidade Federal do ABC" },
  { sigla: "UFOP", nome: "Universidade Federal de Ouro Preto" },
  { sigla: "UFLA", nome: "Universidade Federal de Lavras" },
  { sigla: "UFCSPA", nome: "Universidade Federal de Ciências da Saúde de Porto Alegre" },
  { sigla: "UnB", nome: "Universidade de Brasília" },
  { sigla: "UNESP", nome: "Universidade Estadual Paulista" },
  { sigla: "UNICAMP", nome: "Universidade Estadual de Campinas" },
  { sigla: "UNIFESP", nome: "Universidade Federal de São Paulo" },
  { sigla: "UNINASSAU", nome: "Centro Universitário Maurício de Nassau" },
  { sigla: "UNINOVE", nome: "Universidade Nove de Julho" },
  { sigla: "UNIP", nome: "Universidade Paulista" },
  { sigla: "UNIRIO", nome: "Universidade Federal do Estado do Rio de Janeiro" },
  { sigla: "UNISINOS", nome: "Universidade do Vale do Rio dos Sinos" },
  { sigla: "UNIVALI", nome: "Universidade do Vale do Itajaí" },
  { sigla: "UTFPR", nome: "Universidade Tecnológica Federal do Paraná" },
  { sigla: "USP", nome: "Universidade de São Paulo" },
  { sigla: "USJT", nome: "Universidade São Judas Tadeu" },
  { sigla: "UEA", nome: "Universidade do Estado do Amazonas" },
  { sigla: "UEPB", nome: "Universidade Estadual da Paraíba" },
  { sigla: "UECE", nome: "Universidade Estadual do Ceará" },
  { sigla: "UESC", nome: "Universidade Estadual de Santa Cruz" },
  { sigla: "UESB", nome: "Universidade Estadual do Sudoeste da Bahia" },
  { sigla: "UEFS", nome: "Universidade Estadual de Feira de Santana" },
  { sigla: "UEMA", nome: "Universidade Estadual do Maranhão" },
  { sigla: "UEMG", nome: "Universidade do Estado de Minas Gerais" },
  { sigla: "UEMS", nome: "Universidade Estadual de Mato Grosso do Sul" },
  { sigla: "UDESC", nome: "Universidade do Estado de Santa Catarina" },
  { sigla: "URCA", nome: "Universidade Regional do Cariri" },
  { sigla: "URFN", nome: "Universidade Regional do Rio Grande do Norte" },
  { sigla: "URI", nome: "Universidade Regional Integrada do Alto Uruguai e das Missões" },
  { sigla: "UCB", nome: "Universidade Católica de Brasília" },
  { sigla: "UCS", nome: "Universidade de Caxias do Sul" },
  { sigla: "UCPel", nome: "Universidade Católica de Pelotas" },
  { sigla: "UCSal", nome: "Universidade Católica do Salvador" },
  { sigla: "UFSB", nome: "Universidade Federal do Sul da Bahia" },
  { sigla: "UFCA", nome: "Universidade Federal do Cariri" },
  { sigla: "UFOPA", nome: "Universidade Federal do Oeste do Pará" },
  { sigla: "UNIFEI", nome: "Universidade Federal de Itajubá" },
  { sigla: "UFTM", nome: "Universidade Federal do Triângulo Mineiro" },
  { sigla: "UFVJM", nome: "Universidade Federal dos Vales do Jequitinhonha e Mucuri" },
  { sigla: "IFSP", nome: "Instituto Federal de São Paulo" },
  { sigla: "IFRJ", nome: "Instituto Federal do Rio de Janeiro" },
  { sigla: "IFMG", nome: "Instituto Federal de Minas Gerais" },
  { sigla: "IFPR", nome: "Instituto Federal do Paraná" },
  { sigla: "IFBA", nome: "Instituto Federal da Bahia" },
  { sigla: "IFCE", nome: "Instituto Federal do Ceará" },
  { sigla: "IME", nome: "Instituto Militar de Engenharia" },
  { sigla: "ITA", nome: "Instituto Tecnológico de Aeronáutica" },
];

export function formatInstituicao(i: Instituicao): string {
  return `${i.sigla} - ${i.nome}`;
}
